= Adoptium API Cookbook

The Adoptium API is a powerful tool for downloading the Temurin Java builds. It provides stable URLs that can be embedded into webpages, or used in scripts to automate the querying and downloading of information.

This document shows some simple and popular uses of the Adoptium API to achieve specific goals. See the
https://api.adoptium.net/q/swagger-ui/[full API documentation]
to build more complex queries, including access to nightly builds, debug builds, and sources.

== Example One: Download the latest JDK

To download the latest long-term supported (LTS) Linux x64 JDK version 17 you can use the following stable URL

[source, bash]
----
https://api.adoptium.net/v3/binary/latest/17/ga/linux/x64/jdk/hotspot/normal/eclipse
----

Looking at this URL you can see it follows a general structure with replaceable variables:
`https://api.adoptium.net/v3/binary/latest/{feature_version}/ga/{os}/{arch}/{image_type}/hotspot/normal/eclipse`

so downloading for other Java API versions and platforms is simply replacing the variables with the following options

[unordered.stack]
feature_version:: the Java API version, choose one of "8", "11", "17", "19" and so on.
os:: the operating system, one of "linux", "windows", "mac", "solaris", "aix", or "alpine-linux".
arch:: the CPU architecture, one of "x64", "x86", "x32", "ppc64", "ppc64le", "s390x", "aarch64", "arm", "sparcv9", or "riscv64".
image_type:: product type, choose one of "jdk" or "jre".
 
Not all combinations are valid, so if there is no Temurin build available for the combination you specify the API will return a `HTTP/1.1 404 Not Found` response.


== Example Two: Scripting the download

You can download Temurin binaries and check they were received successfully using a shell script, as folllows:

[source, bash]
----
#!/bin/bash
set -eu
API_URL="https://api.adoptium.net/v3/binary/latest/17/ga/linux/x64/jdk/hotspot/normal/eclipse"

# Fetch the archive
FETCH_URL=$(curl -s -w %{redirect_url} "${API_URL}")
FILENAME=$(curl -OLs -w %{filename_effective} "${FETCH_URL}")

# Validate the checksum
SHA_URL=${FETCH_URL}.sha256.txt
curl -Ls "${SHA_URL}" | sha256sum -c --status

echo "Downloaded successfully as ${FILENAME}"
----

Again, the download URL can be adapted for different Java versions etc. as shown in Example One.
