= Adoptium API Cookbook

The Adoptium API is a powerful tool for downloading the Temurin Java builds. It provides stable URLs that can be embedded into webpages, or used in scripts to automate the querying and downloading of information.

This document shows some simple and popular uses of the Adoptium API to achieve specific goals. See the
https://api.adoptium.net/q/swagger-ui/[full API documentation]
to build more complex queries, including access to nightly builds, debug builds, and sources.

[#example-one]
== Example One: Download the latest JDK

To download the latest long-term supported (LTS) Linux x64 JDK version 17 you can use the following stable URL

[source, html]
----
https://api.adoptium.net/v3/binary/latest/17/ga/linux/x64/jdk/hotspot/normal/eclipse
----

****
Looking at this URL you can see it follows a general structure with replaceable variables:
`https://api.adoptium.net/v3/binary/latest/{feature_version}/ga/{os}/{arch}/{image_type}/hotspot/normal/eclipse`

so downloading for other Java API versions and platforms is simply replacing the variables with the following options

[unordered.stack]
feature_version:: the Java API version, choose one of "8", "11", "17", "19" and so on.
os:: the operating system, one of "linux", "windows", "mac", "solaris", "aix", or "alpine-linux".
arch:: the CPU architecture, one of "x64", "x86", "x32", "ppc64", "ppc64le", "s390x", "aarch64", "arm", "sparcv9", or "riscv64".
image_type:: product type, choose one of "jdk" or "jre".
 
[NOTE]
Not all combinations of vales are valid, so if there is no Temurin build available for the combination you specify the API will return a `HTTP/1.1 404 Not Found` response.
****

== Example Two: Scripting the download

You can download Temurin binaries and check they were received successfully using a shell script, as folllows:

[source, bash]
----
#!/bin/bash
set -eu
API_URL="https://api.adoptium.net/v3/binary/latest/17/ga/linux/x64/jdk/hotspot/normal/eclipse"

# Fetch the archive
FETCH_URL=$(curl -s -w %{redirect_url} "${API_URL}")
FILENAME=$(curl -OLs -w %{filename_effective} "${FETCH_URL}")

# Validate the checksum
curl -Ls "${FETCH_URL}.sha256.txt" | sha256sum -c --status

echo "Downloaded successfully as ${FILENAME}"
----

Again, the download URL can be adapted for different Java versions etc. as shown in <<example-one,Example One>>.

== Example Three: Explore available releases

The API can tell you which releases are available for Temurin, which are long term supported builds, and the latest tip development build, as follows:

[source, html]
https://api.adoptium.net/v3/info/available_releases

which provides a JSON formatted response such as this:

[source, json]
----
{
  "available_lts_releases": [
    8,
    11,
    17
  ],
  "available_releases": [
    8,
    11,
    16,
    17,
    18,
    19
  ],
  "most_recent_feature_release": 19,
  "most_recent_feature_version": 20,
  "most_recent_lts": 17,
  "tip_version": 21
}
----

== Example Four: Find all Windows builds for Java 19

The API can be supplemented to filter the details response by Java version, platform, and other conditions. For example, to find all builds of Java 19 or later for Windows 32-bit architecture, you can use:

[source,html]
https://api.adoptium.net/v3/assets/version/%5B19%2C%5D?os=windows&architecture=x32

[TIP]
The string `%5B17%2C%5D` is a 
https://www.urldecoder.org/[URL encoding] of "[19," which
https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html[describes the version range] "19 onwards".

The full set of filters and possible argument values is available in
https://api.adoptium.net/q/swagger-ui/[the API documentation].

== Example Five: Extract JSON information from the API results

It may be convenient to extract part of the data from an Adoptium API call, and this example shows how to do that using
https://stedolan.github.io/jq/[the `jq` tool] that is broadly available.

Get the most recent LTS version available:

[source, bash]
----
$ curl -s https://api.adoptium.net/v3/info/available_releases | jq '.most_recent_lts'
17
----






== Example Five: Detailed build information for a range of builds

https://api.adoptium.net/v3/assets/version/%5B20%2C%29
