name: OSSF Scorecard
on:
  push:
    branches:
      - main
    workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
    - uses: ossf/scorecard-action@99c53751e09b9529366343771cc321ec74e9bd3d # v2.0.6
      with:
        results_file: results.sarif
        results_format: sarif
    - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
      with:
        name: SARIF file
        path: results.sarif
        retention-days: 5
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
